sudo: false
language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.12.5
deploy:
  provider: rubygems
  api_key:
    secure: your_secure_key
  gem: parxer
  on:
    tags: true
    repo: platanus/parxer
